const {sequelize,DataTypes} = require('../connection')


const GeneralSetting = sequelize.define('general_setting',{
  id:{
    type:DataTypes.INTEGER,
    autoIncrement:true,
    allowNull:false,
    primaryKey:true
  },
  name:{
    type:DataTypes.STRING,
    allowNull:false
  },
  address:{
    type:DataTypes.STRING,
    allowNull:false
  },
  school_code:{
    type:DataTypes.STRING,
    allowNull:false
  },
  phone:{
    type:DataTypes.STRING,
    allowNull:false
  },
  email:{
    type:DataTypes.STRING,
    allowNull:false,
    validate:{
      isEmail:true
    }
  },
  session_start_month:{
    type:DataTypes.STRING,
    // allowNull:false
  },
  attendence:{
    type:DataTypes.ENUM('Day Wise','Period Wise'),
    // allowNull:false
  },
  biometric_attendence:{
    type:DataTypes.ENUM('ENABLED','DISABLED'),
  },
  devices:{
    type:DataTypes.STRING,
    // allowNull:false
  },
  language:{
    type:DataTypes.STRING,
  },
  language_rtl_text_mode:{
    type:DataTypes.ENUM('ENABLED','DISABLED'),
  },
  date_time_format:{
    type:DataTypes.ENUM(
      'dd-mm-yyyy','dd-mmm-yyyy','dd/mm/yyyy','dd.mm.yyyy',
      'mm-dd-yyyy','mm/dd/yyyy','mm.dd.yyyy','yyyy/mm/dd'
    )
  },
  timezone:{
    type:DataTypes.STRING,
    allowNull:false
  },
  currency:{
      type:DataTypes.STRING,
      allowNull:false
  },
  currency_symbol:{
    type:DataTypes.STRING,
    allowNull:false
  },
  auto_admission_no:{
    type:DataTypes.ENUM('ENABLED','DISABLED'),
    allowNull:false
  },
  admmission_no_prefix:{
    type:DataTypes.STRING,
    allowNull:true
  },
  admission_no_digit:{
    type:DataTypes.INTEGER,
    defaultValue:4,
    validate:{
      min:1
    },
  },
  admission_id_start_from:{
    type:DataTypes.STRING,
    default:0001
  },
  auto_staff_id:{
    type:DataTypes.ENUM('ENABLED','DISABLED'),
    defaultValue:'ENABLED'
  },
  staff_id_prefix:{
    type:DataTypes.STRING,
    allowNull:false
  },
  staff_no_digit:{
    type:DataTypes.INTEGER,
    defaultValue:4,
    validate:{
      min:1
    },
  },
  staff_id_start_from:{
    type:DataTypes.STRING,
  },
  duplicate_fees_invoice:{
    type:DataTypes.ENUM('ENABLED','DISABLED'),
    defaultValue:'ENABLED'
  },
  fees_due_days:{
    type:DataTypes.INTEGER,
    allowNull:false
  },
  online_addmission:{
    type:DataTypes.ENUM('ENABLED','DISABLED'),
    defaultValue:'ENABLED'
  },
  teacher_restricted_mode:{
    type:DataTypes.ENUM('ENABLED','DISABLED'),
    defaultValue:'ENABLED'
  },
  mobile_app_url:{
    type:DataTypes.STRING,
  },
  mobile_app_primary_color:{
    type:DataTypes.STRING,
  },
  mobile_app_secondary_color:{
    type:DataTypes.STRING,
  },
  logo:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  favicon:{
    type:DataTypes.STRING,
    defaultValue:null
  }
})

// GeneralSetting.sync({alter:true})

module.exports = GeneralSetting

