const {sequelize, DataTypes} = require('../connection')

const onlineAdmission = sequelize.define('online_admission',{

  id:{
    type:DataTypes.INTEGER,
    autoIncrement:true,
    allowNull:false,
    primaryKey:true
  },
  student_no:{
    type:DataTypes.STRING,
    defaultValue:null,
    unique:true
  },
  id_no:{
    type:DataTypes.STRING,
    defaultValue:null,
    unique:true
  },
  admission_date:{
    type:DataTypes.DATEONLY,
    defaultValue:null
  },
  program:{
    type:DataTypes.INTEGER,
    allowNull:false
  },
  firstname:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  lastname:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  rte:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  image:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  mobileno:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  email:{
    type:DataTypes.STRING,
    defaultValue:null,
    validate:{
      isEmail:true
    }
  },
  state:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  city:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  pincode:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  religion:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  cast:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  dob:{
    type:DataTypes.DATE,
    defaultValue:null
  },
  gender:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  current_address:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  permanent_address:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  category_id:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  route_id:{
    type:DataTypes.INTEGER,
    allowNull:true
  },
  school_house_id:{
    type:DataTypes.INTEGER,
    allowNull:false
  },
  blood_group:{
    type:DataTypes.STRING,
    allowNull:false
  },
  vehroute_id:{
    type:DataTypes.INTEGER,
    allowNull:true
  },
  hostel_room_id:{
    type:DataTypes.INTEGER,
    allowNull:false
  },
  adhar_no:{
    type:DataTypes.STRING,
    defaultValue:null,
    unique:true
  },
  samagra_id:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  bank_account_no:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  bank_name:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  ifsc_code:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  guardian_is:{
    type:DataTypes.STRING,
    allowNull:false
  },
  father_name:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  father_phone:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  father_occupation:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  mother_name:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  mother_phone:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  mother_occupation:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  gaurdian_name:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  gaurdian_phone:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  gaurdian_occupation:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  gaurdian_email:{
    type:DataTypes.STRING,
    allowNull:true,
    validate:{
      isEmail:true
    }
  },
  gaurdian_relation:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  gaurdian_address:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  father_pic:{
    type:DataTypes.STRING,
    allowNull:false
  },
  mother_pic:{
    type:DataTypes.STRING,
    allowNull:false
  },
  gaurdian_pic:{
    type:DataTypes.STRING,
    allowNull:false
  },
  is_active:{
    type:DataTypes.STRING,
    defaultValue:'yes'
  },
  previous_school:{
    type:DataTypes.STRING,
  },
  height:{
    type:DataTypes.STRING,
    allowNull:false
  },
  weight:{
    type:DataTypes.STRING,
    allowNull:false
  },
  measurement_date:{
    type:DataTypes.DATEONLY,
    allowNull:true,
    defaultValue:null
  },
  dis_reason:{
    type:DataTypes.INTEGER,
    allowNull:true
  },
  note:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  app_key:{
    type:DataTypes.STRING
  },
  batch_id:{
    type:DataTypes.INTEGER,
    allowNull:true,
    defaultValue:null
  },
parent_app_key:{
  type:DataTypes.STRING
},
disable_at:{
  type:DataTypes.DATEONLY,
  allowNull:false
},
id_number:{
  type:DataTypes.STRING,
  defaultValue:null
}

})



module.exports = onlineAdmission