const {sequelize,DataTypes} = require('../connection')

const Staff = sequelize.define('staff',{

  id:{
    type:DataTypes.INTEGER,
    autoIncrement:true,
    allowNull:false,
    primaryKey:true
  },
  role:{
    type:DataTypes.INTEGER,
    references:{
      model:'user_roles',
      key:'id'
    }
  },
  designation_id:{
    type:DataTypes.INTEGER,
    references:{
      model:'staff_designations',
      key:'id'
    }
  },
  category_id:{
    type:DataTypes.INTEGER,
    references:{
      model:'categories',
      key:'id'
    }
  },
  department_id:{
    type:DataTypes.INTEGER,
    references:{
      model:'departments',
      key:'id'
    }
  },
  employee_id:{
    type:DataTypes.STRING,
    allowNull:false
  },
  name:{
    type:DataTypes.STRING,
    allowNull:false
  },
  surname:{
    type:DataTypes.STRING,
    allowNull:false
  },
  father_name:{
    type:DataTypes.STRING,
    allowNull:false
  },
  mother_name:{
    type:DataTypes.STRING,
    allowNull:false
  },
  contact_no:{
    type:DataTypes.STRING,
    allowNull:false
  },
  emergency_contact_no:{
    type:DataTypes.STRING,
    allowNull:false
  },
  email:{
    type:DataTypes.STRING,
    allowNull:false,
    validate:{
      isEmail:true
    }
  },
  dob:{
    type:DataTypes.DATEONLY,
    allowNull:false
  },
  martial_status:{
    type:DataTypes.STRING,
    allowNull:false
  },
  date_of_joining:{
    type:DataTypes.DATEONLY,
    allowNull:false
  },
  date_of_leaving:{
    type:DataTypes.DATEONLY,
    allowNull:false
  },
  local_address:{
    type:DataTypes.STRING,
    allowNull:false
  },
  permanent_address:{
    type:DataTypes.STRING,
    allowNull:false
  },
  note:{ type:DataTypes.STRING,
    allowNull:false

  },
  image:{
    type:DataTypes.STRING,
    allowNull:false
  },
  password:{
    type:DataTypes.STRING,
    allowNull:false
  },
  gender:{
    type:DataTypes.STRING,
    allowNull:false
  },
  account_title:{
    type:DataTypes.STRING,
    allowNull:false
  },
  bank_account_no:{
    type:DataTypes.STRING,
    allowNull:false
  },
  bank_name:{
    type:DataTypes.STRING,
    allowNull:false
  },
  ifsc_code:{
    type:DataTypes.STRING,
    allowNull:false
  },
  branch_name:{
    type:DataTypes.STRING,
    allowNull:false
  },
  payscale:{
    type:DataTypes.STRING,
    allowNull:false
  },
  basic_salary:{
    type:DataTypes.STRING,
    allowNull:false
  },
  epf_no:{
    type:DataTypes.STRING,
    allowNull:false
  },
  contract_type:{
    type:DataTypes.STRING,
    allowNull:false
  },
  shift:{
    type:DataTypes.STRING,
    allowNull:false
  },
  location:{
    type:DataTypes.STRING,
    allowNull:false
  },
  facebook:{
    type:DataTypes.STRING,
    allowNull:false
  },
  instagram:{
    type:DataTypes.STRING,
    allowNull:false
  },
  linkedin:{
    type:DataTypes.STRING,
    allowNull:false
  },
  twitter:{
    type:DataTypes.STRING,
    allowNull:false
  },
  resume:{
    type:DataTypes.STRING,
    allowNull:false
  },
  joining_letter:{
    type:DataTypes.STRING,
    allowNull:false
  },
  resignation_letter:{
    type:DataTypes.STRING,
    allowNull:false
  },
  other_document_name:{
    type:DataTypes.STRING,
    allowNull:false
  },
  other_document_file:{
    type:DataTypes.STRING,
    allowNull:false
  },
  user_id:{
    type:DataTypes.INTEGER,
    allowNull:false
  },
  is_active:{
    type:DataTypes.ENUM('yes','no'),
    defaultValue:'yes'
  },
  verification_code:{
    type:DataTypes.STRING,
    allowNull:false
  },
  zoom_api_key:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  zoom_api_secret:{
    type:DataTypes.STRING,
    defaultValue:null
  },
  desable_at:{
    type:DataTypes.DATEONLY,
    defaultValue:null
  }

})


module.exports = Staff